# general conf
CONFIG_GPIO=y

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y

CONFIG_REBOOT=y

# can conf
CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y
CONFIG_CAN_MAX_FILTER=8

CONFIG_ISO14229=y
CONFIG_ISO14229_FUNC_RX_ID=0x7DF
CONFIG_ISO14229_LOG_LEVEL=0
CONFIG_ISO14229_RX_ID=0x7E8
CONFIG_ISO14229_TX_ID=0x7E0

CONFIG_UDS_CAN_BITRATE=500000
CONFIG_UDS_CAN_SAMPLEPOINT=750
