#!/usr/bin/env python

import udsoncan
import isotp
from udsoncan.connections import IsoTPSocketConnection
from udsoncan.client import Client
from udsoncan.exceptions import *
from udsoncan.services import *

udsoncan.setup_logging()

conn = IsoTPSocketConnection('can0', isotp.Address(isotp.AddressingMode.Normal_11bits, rxid=0x7E0, txid=0x7E8))
with Client(conn,  request_timeout=2) as client:
    try:
        # client.change_session(DiagnosticSessionControl.Session.extendedDiagnosticSession)  # integer with value of 3
        # client.unlock_security_access(5)   # Fictive security level. Integer coming from fictive lib, let's say its value is 5
        client.ecu_reset(ECUReset.ResetType.hardReset)  # HardReset = 0x01
    except NegativeResponseException as e:
        print('Server refused our request for service %s with code "%s" (0x%02x)' % (e.response.service.get_name(), e.response.code_name, e.response.code))
    except (InvalidResponseException, UnexpectedResponseException) as e:
        print('Server sent an invalid payload : %s' % e.response.original_payload)
